### ISSUE TITLE
is this lib supposed to work with Stripe's test webhooks at all?

### ISSUE THREAD

**Issue by mezod** [jsonmaur/stripe-local#3]
Hi,

I stumbled upon this lib trying to test Stripe's test webhooks with my local machine.

I understand this might be caused by my poor understanding but it's been a bit confusing. 

If I understood correctly, and the library doesn't use Stripe test webhooks at all, it would be very helpful to change the first line and make it obvious that the library isn't using webhooks at all but just locally generating/mimicking them.

I am still unsure, so please correct me if I am wrong, but the way I see it the first line is simply wrong and very misleading.

This library just takes the event list from ANY ENVIRONMENT from a local machine to locally generate something acting as a webhook to call the endpoint. I am not even sure what's the use case really.

I'm so confused I'm sure I'm wrong, so please correct me! 

Take this as feedback :)

**Comment by jsonmaur** [comment]
> Uses real events from your Stripe account by polling for them at a defined interval

Doesn't use real webhooks--it simulates them. I agree that the first line is misleading, but I never really intended this to be widely used. Stripe webhooks can't connect to a LAN endpoint without using a tunnel, and this was a workaround to simulate the behavior for a project I was working on at the time. Haven't touched this library since, and I'm sure there is a better way to do it now :)
